export const FETCH_WEATHER_PENDING = "FETCH_WEATHER_PENDING"

export const FETCH_FORECAST_SUCCESS = "FETCH_FORECAST_SUCCESS"
export const FETCH_CURRENT_SUCCESS = "FETCH_CURRENT_SUCCESS"

export const FETCH_WEATHER_ERROR = "FETCH_WEATHER_ERROR"
export const SET_CITY = "SET_CITY";